# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "SIGINT-185-Configure_GitHub_Workflow_to_use_bridge_via_configuration_for_Altair" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, kishor]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Use synopsys unified-action
        # Use the action defined in this repository
        env:
          BRIDGE_polaris_accessToken: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          BRIDGE_polaris_serverUrl: ${{ secrets.POLARIS_SEVER_URL }}
          BRIDGE_polaris_application_name: testapp1
          BRIDGE_polaris_project_name: testproj1
          BRIDGE_polaris_assessment_types: "[\"SAST\"]"
          BRIDGE_URL: "https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/polaris-ci/0.1.60/polaris-ci-0.1.60-macosx.zip"
        run: |
          curl -o bridge.zip -L $BRIDGE_URL
          7z x bridge.zip
          bridge --stage polaris
#        uses: ./
#        with:
#          polaris-server-url: ${{ secrets.POLARIS_SEVER_URL }}
#          polaris-access-token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
#          polaris-application-name: "testapp1"
#          polaris-project-name: "testproj1"
#          polaris-assessment-types: "SAST"
